version: 2.1

jobs:

  pages:
    docker:
    - image: python:latest
    steps:
    - checkout
    - run: python3 -V
    - run: pip3 install .
    - run: pip3 install sphinx
    - run: pip3 install sphinx-rtd-theme
    - run: pip3 install sphinxcontrib-autoprogram
    - run: sphinx-build -aETb html docs/source docs/build/html
    - run: sphinx-build -aETb html docs/source docs/stable
    - run: sphinx-build -aETb html docs/source docs/$(date +%Y.%m)
#    - run: cp -r docs/$(date +%Y.%m) docs/build/html
#    - run: cp -r docs/$(date +%Y.%m) docs/stable
    - run: git add --all
    - run: git commit -m "Publishing updated documentation."
    # git credentials?
    - run: git push origin gh-pages

#  tests:
#    docker:
#    - image: python:latest
#    steps:
#    - checkout
#    - run: python -V

workflows:
  version: 2

#  testing:
#    triggers:
#      branches:
#        ignore:
#          - master
#          - stable
#          - gh-pages
#    jobs:
#      - tests

  deploy:
    jobs:
      - pages:
          filters:
            branches:
              only: stable
