version: 2.1

jobs:

#  unit-testing:
#    docker:
#    - image: python:latest
#    steps:
#    - checkout
#    - run: python -V

#  auto-release:
#    docker:
#      - image: python:latest
#    steps:
#      - add_ssh_keys:
#          fingerprints:
#            - "4a:30:b4:68:a8:21:16:35:b1:81:90:5f:39:56:32:1b"
#      - checkout
#      - run: version=$(date +%Y.%m)
#      - run: $version > VERSION
#      - run: git config --global user.email "$GH_EMAIL"
#      - run: git config --global user.name "$GH_NAME"
#      - run: git add --all
#      - run: git tag v$version
#      - run: git commit -m "[skip ci] version update."
#      - run: git push -f origin master

  publish-docs:
    docker:
      - image: python:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:30:b4:68:a8:21:16:35:b1:81:90:5f:39:56:32:1b"
      - checkout
      - run:
          name: "Install Package"
          command: pip3 install .
      - run:
          name: "Install Sphinx"
          command: |
            pip3 install git+https://github.com/sphinx-doc/sphinx
            pip3 install sphinxcontrib-autoprogram
            pip3 install sphinx-rtd-theme
      - run:
          name: "Set Git Variables"
          command: |
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
      - run:
          name: "Generate Docs"
          command: |
            sphinx-build -aETb html docs/source docs/stable
            sphinx-build -aETb html docs/source docs/$(cat VERSION)
      - run:
          name: "Commit New Docs"
          command: |
            git add -f docs
            git commit -m "[skip ci] documentation build."
      - run:
          name: "Push to GitHub"
          command: |
            git checkout -b old origin/gh-pages
            git merge new

            git push -f origin new:gh-pages

workflows:
  version: 2

#  testing:
#    jobs:
#      - unit-testing:
#          filters:
#            branches:
#              ignore:
#                - gh-pages

  release:
    jobs:
#      - unit-testing:
#          filters:
#            branches:
#              ignore:
#                - gh-pages
#      - auto-release:
#          requires:
#            - unit-testing
#          filters:
#            branches:
#              only: master
      - publish-docs:
#          requires:
#            - auto-release
          filters:
            branches:
              only: master
