jobs:

  # For documentation deployment. You'll need the following environment vars
  # in your Circle CI settings, otherwise this will not work.
  #
  # GH_NAME (your git username)
  # GH_EMAIL (your git email)
  # GH_TOKEN (the personal Git token with pushes enabled)
  build-docs:
    docker:
    - image: python:3.6
    steps:
    - checkout

workflows:
  version: 2

  # Todo: put testing jobs here
  # testing:
  #   jobs:

  # All deployment
  deploy:
    jobs:
      - build-docs
