jobs:

  # For documentation deployment. You'll need the following environment vars
  # in your Circle CI settings, otherwise this will not work.
  #
  # GH_NAME (your git username)
  # GH_EMAIL (your git email)
  # GH_TOKEN (the personal Git token with pushes enabled)
  pages:
    docker:
    - image: python:latest
    steps:
    - checkout
    - run: python -V
    - run: pip3 install . sphinx sphinx-rtd-theme
    - run: sphinx-build -aETb html docs/source docs/build/html

workflows:
  version: 2

  # Todo: put testing jobs here
  # testing:
  #   jobs:

  # All deployment
  deploy:
    jobs:
      - pages
