version: 2.1

jobs:

  check-python:
    docker:
      - image: python:latest
    steps:
      - run:
          name: "Check Python and Pip versions"
          command: |
            python3 --version
            pip3 --version

  unit-testing:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          name: "Install packages and run unit tests"
          command: |
            pip3 install pytest
            pip3 install pytest-cov
            pip3 install pytest-circleci
            pip3 install . --verbose
            pytest tests --junitxml="tests/reports/results.xml"
      - store_test_results:
          path: tests/reports

  push-dev-tag:
    docker:
      - image: python:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:30:b4:68:a8:21:16:35:b1:81:90:5f:39:56:32:1b"
      - checkout
      - run:
          name: "Create new tag and push to GitHub"
          command: |
            set -x
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
            month=$(date +%Y.%m)
            latest=$(git describe --tags --abbrev=0)
            branch=$(git rev-parse --abbrev-ref HEAD)
            type=$(if [[ $branch == master ]]; then echo rc; else echo .dev; fi)
            next=$(expr $(echo $latest | grep -oP "(?<=^v${month}${type})\d+$") + 1)
            version="v${month}${type}${next}"
            git tag $version
            git push origin $version

  publish-docs:
    docker:
      - image: python:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:30:b4:68:a8:21:16:35:b1:81:90:5f:39:56:32:1b"
      - checkout
      - run:
          name: "Build HTML docs and push to GitHub"
          command: |
            set -x
            pip3 install . --verbose
            pip3 install sphinx>=3
            pip3 install sphinxcontrib-autoprogram
            pip3 install sphinx-rtd-theme
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
            latest=$(git describe --tags --abbrev=0)
            version=$(echo $latest | grep -oP "^v\d+\.\d+")
            sphinx-build -aETb html docs/source docs/latest -D version=latest -D release=latest
            sphinx-build -aETb html docs/source docs/$version -D version=$version -D release=$latest
            git add -f docs
            git stash
            git pull origin gh-pages --no-commit
            git checkout stash -- .
            git commit -m "[skip ci] documentation build."
            git push -f origin $(git rev-parse --abbrev-ref HEAD):gh-pages

  build-deploy:
    docker:
      - image: python:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:30:b4:68:a8:21:16:35:b1:81:90:5f:39:56:32:1b"
      - checkout
      - run:
          name: "Build release and upload to PyPI"
          command: |
            - set -x
            - pip3 install twine
            - version=$(date +%Y.%m -d "$(date +%Y-%m-01)-1 day")
            - latest=$(git describe --tags --abbrev=0)
            - if [[ $(echo $latest | grep -oP "(?<=^v)\d+\.\d+(?=rc\d+$)") == $version ]];
            - then
            - git tag --force $version;
            - git push --force origin $version;
            - python3 setup.py sdist;
            - python3 setup.py bdist_wheel;
#            twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
            - else
            - echo "No new release candidate to deploy.";
            - fi

workflows:
  version: 2

  develop:
    jobs:
      - check-python
      - unit-testing:
          filters:
            branches:
              ignore:
                - gh-pages
      - push-dev-tag:
          requires:
            - unit-testing
          filters:
            branches:
              only:
                - develop
                - master
      - publish-docs:
          requires:
            - unit-testing
            - push-dev-tag
          filters:
            branches:
              only:
                - develop
                - master

  release:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only: master
    jobs:
      - check-python
      - unit-testing
      - build-deploy:
          requires:
            - unit-testing
      - publish-docs:
          requires:
            - unit-testing
            - build-deploy
